CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -pedantic

# all: main parent child
all: main

# parent: parent.c
# 	$(CC) $(CFLAGS) -o $@ $<

# child: child.c
# 	$(CC) $(CFLAGS) -o $@ $<

clean:
	rm -f main parent child myfifo

.PHONY: all clean